server:
  port: 16001

spring:
  application:
    name: sd-gateway
  cloud:
    gateway:
      routes:
        - id: sdUser
          uri: http://localhost:16002/
          predicates:
            - Path=/user/**
        - id: sdBroker
          uri: http://localhost:16003/
          predicates:
            - Path=/broker/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true